[package]
name = "blkchn-file-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
inotify = "0.11.0"
tokio = {version = "1.40.0", features = ["rt-multi-thread", "macros","rt"] }

[build-dependencies]
bindgen = "0.65.1"
walkdir = "2.3.3"
